apiVersion: apps/v1
kind: Deployment
metadata:
  name: devicemgmt
  labels:
    app: devicemgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devicemgmt
  template:
    metadata:
      labels:
        app: devicemgmt
    spec:
      containers:
        - name: devicemgmt
          image: "username/devicemgmt:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
