apiVersion: v1
kind: Service
metadata:
  name: notificationmanagement
  labels:
    app: notificationmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: notificationmanagement