name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./report/pom.xml
          mvn clean package -f ./notificationmanagement/pom.xml
          mvn clean package -f ./devicemgmt/pom.xml
          mvn clean package -f ./analytics/pom.xml

      - name: Docker Build and push for Report
        uses: docker/build-push-action@v4
        with:
          context: ./report
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/report:latest
            ghcr.io/${{ github.repository }}/report:${{ github.ref_name }}
            
      - name: Docker Build and push for Notificationmanagement
        uses: docker/build-push-action@v4
        with:
          context: ./notificationmanagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/notificationmanagement:latest
            ghcr.io/${{ github.repository }}/notificationmanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for Devicemgmt
        uses: docker/build-push-action@v4
        with:
          context: ./devicemgmt
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/devicemgmt:latest
            ghcr.io/${{ github.repository }}/devicemgmt:${{ github.ref_name }}
            
      - name: Docker Build and push for Analytics
        uses: docker/build-push-action@v4
        with:
          context: ./analytics
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/analytics:latest
            ghcr.io/${{ github.repository }}/analytics:${{ github.ref_name }}
            
