---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: report
  labels:
    app: report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report
  template:
    metadata:
      labels:
        app: report
    spec:
      containers:
        - name: report
          image: username/report:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationmanagement
  labels:
    app: notificationmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationmanagement
  template:
    metadata:
      labels:
        app: notificationmanagement
    spec:
      containers:
        - name: notificationmanagement
          image: username/notificationmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devicemgmt
  labels:
    app: devicemgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devicemgmt
  template:
    metadata:
      labels:
        app: devicemgmt
    spec:
      containers:
        - name: devicemgmt
          image: username/devicemgmt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: username/analytics:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: report
  labels:
    app: report
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: report


---


apiVersion: v1
kind: Service
metadata:
  name: notificationmanagement
  labels:
    app: notificationmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: notificationmanagement


---


apiVersion: v1
kind: Service
metadata:
  name: devicemgmt
  labels:
    app: devicemgmt
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: devicemgmt


---


apiVersion: v1
kind: Service
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: analytics

