apiVersion: apps/v1
kind: Deployment
metadata:
  name: device mgmt
  labels:
    app: device mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device mgmt
  template:
    metadata:
      labels:
        app: device mgmt
    spec:
      containers:
        - name: device mgmt
          image: "username/device mgmt:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
